### PR TITLE
feat(app): don't create branch if there are no updates

### LINKED ISSUE #1796: Proposal: Don't create a branch if there's no need
Denopendabot should only create a branch on remote if it's going to open a PR; otherwise, it's just clutter. I can implement this and send a PR if the proposal is accepted.

### PR DESCRIPTION
**Pull request by yardenshoham**
Closes #1796

### CODE REVIEW

**Comment by yardenshoham** [comment]
Will it break this?
https://github.com/hasundue/denopendabot/blob/195f361354bf5e594a5e9bf860d655429f013b44/mod.ts#L184

**Comment by yardenshoham** [comment]
Why isn't it stopping here already?
https://github.com/hasundue/denopendabot/blob/195f361354bf5e594a5e9bf860d655429f013b44/cli.ts#L63-L67

**Comment by hasundue** [comment]
Thank you! I'm gonna review soon.

**Comment by yardenshoham** [comment]
If we don't create the branch won't this fail?
https://github.com/hasundue/denopendabot/blob/195f361354bf5e594a5e9bf860d655429f013b44/mod.ts#L184

**Comment by hasundue** [comment]
> If we don't create the branch won't this fail?
> 
> https://github.com/hasundue/denopendabot/blob/195f361354bf5e594a5e9bf860d655429f013b44/mod.ts#L184

Probably.
Maybe we should make `createCommits` throw an error when `updates` is empty and check the length on the upstream?

**Comment by hasundue** [comment]
> Why isn't it stopping here already?
> 
> https://github.com/hasundue/denopendabot/blob/195f361354bf5e594a5e9bf860d655429f013b44/cli.ts#L63-L67

Oh, there is a check.
I just found the check is missing in the corresponding part of `app.ts`.
You found the bug in the GitHub App, not in the GitHub Action, didn't you?

**Comment by yardenshoham** [comment]
I think I fixed it for both now

**Review by hasundue — APPROVED** [review]

**Pull request merged**
